sub-color='#FFFF00' #subtitle color in rgb
sub-shadow-color='#d3d3d3' #shadow color 
sub-font='Noto Sans' #set font
sub-blur=4

glsl-shaders="C:\Users\meh\Documents\Code\App\fount\mpv\shaders\test_pattern.glsl"
